websites:
  - "https://example1.com"
  - "https://example2.com"
check_interval: 1m
email:
  smtpServer: "smtp.example.com"
  smtpPort: "587"
  sender: "your-email@example.com"
  password: "your-email-password"
  receiver: "recipient-email@example.com"
